<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import type { CourseGroup, CourseUnit, Presentation, PPTTemplate } from '#root/types';
import { aiService } from '@/services/aiService';
import { toast } from '@/utils/toast';
import LucideIcon from '@/components/common/LucideIcon.vue';
import PptxGenJS from 'pptxgenjs';

interface Props {
  currentCourse: CourseGroup;
  currentUnit: CourseUnit | null;
}

interface Emits {
  (e: 'updateUnit', unitId: string, updates: Partial<CourseUnit>): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();
const { t } = useI18n();

const loading = ref(false);
const presentation = ref<Presentation | null>(null);
const currentSlideIndex = ref(0);
const templates = ref<PPTTemplate[]>([]);
const selectedTemplateId = ref('');
const viewState = ref<'SELECT_TEMPLATE' | 'PREVIEW'>('SELECT_TEMPLATE');

const hasOutline = computed(() => !!props.currentUnit?.outlineContent);
const selectedTemplate = computed(() => templates.value.find((item) => item.id === selectedTemplateId.value) || null);
const slides = computed(() => presentation.value?.slides ?? []);
const currentSlide = computed(() => slides.value[currentSlideIndex.value]);

const ensureSelectedTemplate = (list: PPTTemplate[]) => {
  if (!list.length) return;
  const fallback = list[0];
  if (!fallback) return;
  if (props.currentUnit?.selectedTemplateId) {
    const exists = list.find((item) => item.id === props.currentUnit?.selectedTemplateId);
    selectedTemplateId.value = exists ? exists.id : fallback.id;
    return;
  }
  if (!selectedTemplateId.value) {
    selectedTemplateId.value = fallback.id;
  }
};

const loadTemplates = async () => {
  const list = await aiService.getTemplates();
  templates.value = list;
  ensureSelectedTemplate(list);
};

const syncFromUnit = (unit: CourseUnit | null) => {
  presentation.value = unit?.presentation || null;
  viewState.value = unit?.presentation ? 'PREVIEW' : 'SELECT_TEMPLATE';
  if (unit?.selectedTemplateId) {
    selectedTemplateId.value = unit.selectedTemplateId;
  }
};

onMounted(loadTemplates);

watch(
  () => props.currentUnit,
  (unit) => {
    syncFromUnit(unit);
    if (templates.value.length) {
      ensureSelectedTemplate(templates.value);
    }
  },
  { immediate: true },
);

watch(
  slides,
  (list) => {
    if (currentSlideIndex.value >= list.length) {
      currentSlideIndex.value = list.length ? list.length - 1 : 0;
    }
  },
  { immediate: true },
);

const handleGenerate = async () => {
  const unit = props.currentUnit;
  const template = selectedTemplate.value;
  if (!unit || !unit.outlineContent || !template) return;

  loading.value = true;
  currentSlideIndex.value = 0;
  presentation.value = { theme: template.id, slides: [] };

  try {
    const result = await aiService.generatePPT(
      props.currentCourse,
      unit,
      unit.outlineContent,
      template,
      (newSlide) => {
        presentation.value = {
          theme: template?.id || '',
          slides: [...(presentation.value?.slides || []), { title: newSlide.title, content: newSlide.content, notes: newSlide.notes || '' }],
        };
      },
    );

    presentation.value = result;
    viewState.value = 'PREVIEW';

    emit('updateUnit', unit.id, {
      presentation: result,
      selectedTemplateId: selectedTemplateId.value,
    });
    toast.success(t('ppt.toast.generated'));
  } catch (error) {
    console.error(error);
    toast.error(t('ppt.toast.error'));
  } finally {
    loading.value = false;
  }
};

const downloadMarkdown = () => {
  if (!presentation.value || !props.currentUnit) return;

  const mdContent = presentation.value.slides
    .map(
      (slide, i) => `
# Slide ${i + 1}: ${slide.title}

${slide.content.map((c) => `- ${c}`).join('\n')}

**Speaker Notes:**
${slide.notes}

---
`,
    )
    .join('\n');

  const blob = new Blob([mdContent], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${props.currentUnit.title.replace(/\s+/g, '_')}_Slides.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
  toast.success(t('ppt.toast.markdown'));
};

const downloadPPTX = async () => {
  if (!presentation.value || !props.currentUnit) return;

  const pres = new PptxGenJS();
  pres.layout = 'LAYOUT_16x9';
  pres.author = 'TeachDo AI';
  pres.title = props.currentUnit.title;

  const template = selectedTemplate.value;

  const masterOptions: any = {
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      { rect: { x: 0, y: '96%', w: '100%', h: '4%', fill: { color: 'F8FAFC' } } },
      { text: { text: 'Generated by TeachDo', options: { x: 0.2, y: '97%', fontSize: 9, color: '94A3B8' } } },
    ],
  };

  if (template?.coverUrl) {
    masterOptions.background = { path: template.coverUrl };
  }

  pres.defineSlideMaster(masterOptions);

  presentation.value.slides.forEach((slide) => {
    const s = pres.addSlide({ masterName: 'MASTER_SLIDE' });
    s.addShape(pres.ShapeType.rect, {
      x: '5%',
      y: '15%',
      w: '90%',
      h: '75%',
      fill: { color: 'FFFFFF', transparency: 15 },
      line: { color: 'FFFFFF', width: 0 },
    });

    s.addText(slide.title, {
      x: '7%',
      y: '18%',
      w: '86%',
      h: 1,
      fontSize: 32,
      bold: true,
      color: '1E293B',
      fontFace: 'Arial',
      shadow: { type: 'outer', blur: 3, offset: 2, angle: 45, color: '000000', opacity: 0.1 },
    });

    if (slide.content && slide.content.length > 0) {
      const bullets = slide.content.map((line) => ({
        text: line,
        options: { breakLine: true, indentLevel: 0 },
      }));
      s.addText(bullets, {
        x: '7%',
        y: '32%',
        w: '86%',
        h: '55%',
        fontSize: 20,
        color: '334155',
        bullet: { code: '2022' },
        lineSpacing: 36,
        fontFace: 'Arial',
      });
    }

    if (slide.notes) {
      s.addNotes(slide.notes);
    }
  });

  try {
    await pres.writeFile({ fileName: `${props.currentUnit.title.replace(/\s+/g, '_')}.pptx` });
    toast.success(t('ppt.toast.pptx'));
  } catch (e) {
    console.error('PPT Export failed', e);
    toast.error(t('ppt.toast.pptx_error'));
  }
};
</script>

<template>
  <div v-if="!hasOutline" class="flex-1 flex flex-col items-center justify-center text-slate-400 h-full p-8 border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-3xl bg-slate-50/50 dark:bg-slate-900/30">
    <div class="w-16 h-16 bg-white dark:bg-slate-800 rounded-2xl shadow-sm flex items-center justify-center mb-4">
      <LucideIcon name="presentation" :size="32" class="opacity-60" />
    </div>
    <h3 class="text-lg font-bold text-slate-700 dark:text-slate-300">{{ t('lesson.need_outline.title') }}</h3>
    <p class="text-sm mt-2 mb-6 max-w-md text-center text-slate-500">{{ t('ppt.empty_outline') }}</p>
  </div>

  <div v-else class="h-full flex flex-col gap-6">
    <div v-if="viewState === 'SELECT_TEMPLATE'" class="flex-1 flex flex-col">
      <div class="mb-6">
        <h2 class="text-2xl font-bold text-slate-900 dark:text-white">{{ t('ppt.choose_template') }}</h2>
        <p class="text-slate-500 dark:text-slate-400">{{ t('ppt.select_hint') }}</p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <div
          v-for="template in templates"
          :key="template.id"
          :class="[
            'cursor-pointer group relative rounded-xl overflow-hidden border-2 transition-all',
            selectedTemplateId === template.id ? 'border-indigo-500 ring-4 ring-indigo-500/20 scale-105' : 'border-slate-200 dark:border-slate-800 hover:border-indigo-300',
          ]"
          @click="selectedTemplateId = template.id"
        >
          <div v-if="template.coverUrl" class="h-32 w-full bg-slate-100 overflow-hidden">
            <img :src="template.coverUrl" class="h-full w-full object-cover group-hover:scale-110 transition-transform duration-500" :alt="template.name" />
          </div>
          <div v-else :class="['h-32 w-full flex items-center justify-center', template.thumbnailColor]">
            <span class="text-white font-bold opacity-80 text-lg">Aa</span>
          </div>
          <div class="p-4 bg-white dark:bg-slate-900">
            <h3 class="font-bold text-slate-800 dark:text-white">{{ template.name }}</h3>
            <p class="text-xs text-slate-500 mt-1">{{ template.styleDescription }}</p>
          </div>
          <div v-if="selectedTemplateId === template.id" class="absolute top-2 right-2 bg-indigo-500 text-white rounded-full p-1 shadow-lg">
            <LucideIcon name="check" :size="16" />
          </div>
        </div>
      </div>

      <div class="flex justify-center">
        <button
          :disabled="loading || !templates.length"
          class="px-10 py-4 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-300 disabled:text-slate-500 text-white rounded-2xl font-bold text-lg shadow-xl shadow-indigo-500/30 transition-all flex items-center gap-3"
          @click="handleGenerate"
        >
          <LucideIcon v-if="loading" name="loader-2" :size="20" class="animate-spin" />
          <span v-else>✨ {{ t('ppt.generate') }}</span>
          <span v-if="loading">{{ t('ppt.generating') }}</span>
        </button>
      </div>
    </div>

    <div v-else class="h-full flex flex-col gap-6">
      <div class="flex justify-between items-center bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div class="flex items-center gap-4">
          <div>
            <h3 class="font-bold text-slate-800 dark:text-white">{{ t('ppt.preview_title') }}</h3>
            <p class="text-xs text-slate-500">{{ t('ppt.slides_generated', { count: presentation?.slides.length || 0 }) }}</p>
          </div>
        </div>
        <div class="flex gap-2 flex-wrap justify-end">
          <button
            type="button"
            class="hidden md:flex px-4 py-2 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 rounded-lg font-bold text-sm hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors items-center gap-2"
            @click="downloadMarkdown"
          >
            <LucideIcon name="file-down" :size="16" /> {{ t('ppt.download_md') }}
          </button>
          <button
            type="button"
            class="px-4 py-2 border border-orange-200 dark:border-orange-900/50 bg-orange-50 dark:bg-orange-900/20 text-orange-700 dark:text-orange-400 rounded-lg font-bold text-sm hover:bg-orange-100 dark:hover:bg-orange-900/30 transition-colors flex items-center gap-2"
            @click="downloadPPTX"
          >
            <LucideIcon name="download" :size="16" /> {{ t('ppt.download_pptx') }}
          </button>
          <div class="w-px h-6 bg-slate-200 dark:bg-slate-700 mx-1" />
          <button
            type="button"
            class="px-4 py-2 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 rounded-lg font-bold text-sm hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
            @click="viewState = 'SELECT_TEMPLATE'"
          >
            {{ t('ppt.change_template') }}
          </button>
          <button
            type="button"
            :disabled="loading"
            class="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-bold text-sm shadow-md transition-all flex items-center gap-2 disabled:bg-slate-300 disabled:text-slate-500"
            @click="handleGenerate"
          >
            <LucideIcon :name="loading ? 'loader-2' : 'refresh-cw'" :size="16" :class="{ 'animate-spin': loading }" />
            <span>{{ loading ? t('ppt.generating') : t('ppt.regenerate') }}</span>
          </button>
        </div>
      </div>

      <div v-if="!presentation || slides.length === 0" class="flex-1 flex items-center justify-center bg-slate-100 dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div class="text-center opacity-40">
          <LucideIcon name="loader-2" :size="48" class="animate-spin mx-auto mb-4" />
          <p class="font-bold">{{ t('ppt.generating_content') }}</p>
        </div>
      </div>

      <div v-else class="flex-1 flex gap-6 overflow-hidden">
        <div class="w-48 flex-shrink-0 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-y-auto custom-scrollbar p-3 space-y-3">
          <button
            v-for="(slide, i) in slides"
            :key="i"
            :class="['w-full text-left group transition-all', currentSlideIndex === i ? 'ring-2 ring-indigo-500 rounded-lg' : 'opacity-70 hover:opacity-100']"
            @click="currentSlideIndex = i"
          >
            <div
              :class="[
                'aspect-video w-full rounded-lg mb-1 flex items-center justify-center text-[10px] p-2 border',
                currentSlideIndex === i ? 'bg-indigo-50 dark:bg-indigo-900/20 border-indigo-200' : 'bg-slate-100 dark:bg-slate-800 border-slate-200',
              ]"
            >
                <div class="text-center line-clamp-2 leading-tight font-bold text-slate-700 dark:text-slate-300">{{ slide.title || t('ppt.untitled') }}</div>
              </div>
              <div class="flex justify-between items-center px-1">
                <span class="text-[10px] font-bold text-slate-400">{{ t('ppt.slide_label', { index: i + 1 }) }}</span>
              </div>
            </button>
          </div>

          <div class="flex-1 flex flex-col bg-slate-100 dark:bg-slate-950 rounded-2xl border border-slate-200 dark:border-slate-800 p-8 overflow-y-auto">
          <div v-if="currentSlide" class="w-full aspect-video bg-white dark:bg-slate-900 shadow-2xl rounded-xl p-12 flex flex-col relative overflow-hidden mb-6 flex-shrink-0 transition-all duration-300">
            <div v-if="selectedTemplate?.coverUrl" class="absolute inset-0 bg-center bg-cover opacity-5 pointer-events-none" :style="{ backgroundImage: `url(${selectedTemplate.coverUrl})` }" />
            <div v-else class="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-20 -mr-20 -mt-20" :class="selectedTemplate?.thumbnailColor || 'bg-slate-200'" />
            <div class="relative z-10 flex flex-col h-full">
              <h1 class="text-4xl font-black text-slate-900 dark:text-white mb-8 leading-tight">
                {{ currentSlide?.title }}
              </h1>
              <div class="flex-1">
                <ul class="space-y-4">
                  <li v-for="(c, idx) in currentSlide?.content || []" :key="idx" class="flex items-start text-xl text-slate-700 dark:text-slate-300">
                    <span class="mr-4 text-indigo-500 mt-1.5">•</span>
                    <span>{{ c }}</span>
                  </li>
                </ul>
              </div>
              <div class="mt-auto flex justify-between items-end border-t border-slate-100 dark:border-slate-800 pt-6">
                <div class="text-sm font-bold text-slate-400 uppercase tracking-widest">TeachDo x AI2PPT</div>
                <div class="text-sm font-bold text-slate-400">{{ currentSlideIndex + 1 }} / {{ slides.length }}</div>
              </div>
            </div>
            </div>

            <div class="bg-white dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800 flex-shrink-0">
              <h4 class="text-xs font-bold text-slate-400 uppercase tracking-widest mb-2">{{ t('ppt.speaker_notes') }}</h4>
              <p class="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
                {{ currentSlide?.notes || t('ppt.no_notes') }}
              </p>
            </div>
          </div>
        </div>
      </div>
  </div>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}

.custom-scrollbar::-webkit-scrollbar-thumb {
  background: rgba(148, 163, 184, 0.3);
  border-radius: 4px;
}

.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: rgba(148, 163, 184, 0.5);
}

.dark .custom-scrollbar::-webkit-scrollbar-thumb {
  background: rgba(71, 85, 105, 0.5);
}

.dark .custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: rgba(71, 85, 105, 0.7);
}
</style>
