#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date  : 2025/9/19 14:49
# @File  : utils.py
# @Author: johnson
# @Contact : github: johnson7788
# @Desc  : PPT Writer / Checker 共用的轻量校验与状态机工具
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

ALLOWED_CHART_TYPES = {"line", "bar", "pie", "column", "ring", "area", "radar"}
PLACEHOLDER_PATTERNS = (
    re.compile(r"^\s*detailed content about\b", re.IGNORECASE),
    re.compile(r"a presentation generated by ai", re.IGNORECASE),
    re.compile(r"^\s*exploring the topic of\b", re.IGNORECASE),
    re.compile(r"\blorem ipsum\b", re.IGNORECASE),
)
PLACEHOLDER_WORDS = {"todo", "tbd", "待补充", "待完善", "示例文本", "占位"}
FAILURE_STAGE_PARSE = "parse"
FAILURE_STAGE_STRUCTURE = "structure"
FAILURE_STAGE_QUALITY = "quality"


@dataclass
class CheckerOutcome:
    passed: bool
    summary_text: str
    feedback: Optional[str]
    issues: List[str]
    failure_stage: Optional[str]
    parsed_data: Optional[dict]
    is_valid_json: bool
    structure_passed: bool
    quality_passed: bool


@dataclass
class ControllerDecision:
    action: str
    retry_count: int
    current_slide_index: int
    next_slide_index: int
    output_text: Optional[str]
    should_escalate: bool
    degraded: bool
    failure_stage: Optional[str]


# ================== JSON 解析与规则校验 ==================
def only_json(text: str) -> Optional[dict]:
    """从文本中尽力截取并解析首个 JSON 对象，失败返回 None。"""
    if not text:
        return None
    text = text.strip()
    try:
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1 and end > start:
            text = text[start : end + 1]
        return json.loads(text)
    except Exception:
        return None


def _dedupe_keep_order(items: List[str]) -> List[str]:
    seen: set[str] = set()
    result: List[str] = []
    for item in items:
        normalized = str(item or "").strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        result.append(normalized)
    return result


def _is_non_empty_string(value: Any, *, min_length: int = 1) -> bool:
    return isinstance(value, str) and len(value.strip()) >= min_length


def _normalize_text(value: Any) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"\s+", " ", text)
    return text


def _looks_like_placeholder(text: Any) -> bool:
    normalized = _normalize_text(text)
    if not normalized:
        return True
    if normalized in PLACEHOLDER_WORDS:
        return True
    return any(pattern.search(normalized) for pattern in PLACEHOLDER_PATTERNS)


def _validate_list_shape(field_path: str, data_value: Any, schema_value: list, issues: List[str]) -> None:
    if not isinstance(data_value, list):
        issues.append(f"{field_path} 应为 list")
        return
    if not schema_value:
        return
    first_schema_item = schema_value[0]
    if isinstance(first_schema_item, dict):
        for index, item in enumerate(data_value):
            if not isinstance(item, dict):
                issues.append(f"{field_path}[{index}] 应为 dict")
    elif isinstance(first_schema_item, str):
        for index, item in enumerate(data_value):
            if not isinstance(item, str):
                issues.append(f"{field_path}[{index}] 应为字符串")


def validate_slide(data: Any, required_schema: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """
    规则校验：
    1. 顶层必须是 dict
    2. 必需字段必须存在
    3. 对 `dict/list/str` 做最小类型校验
    4. 仅深入到第二层（例如 data.*）
    返回 (是否通过, 问题列表)。
    """
    issues: List[str] = []

    if not isinstance(data, dict) or not isinstance(required_schema, dict):
        return False, sorted(list(required_schema.keys()))

    for key, schema_value in required_schema.items():
        if key not in data:
            issues.append(key)
            continue

        current_value = data.get(key)
        if isinstance(schema_value, dict):
            if not isinstance(current_value, dict):
                issues.append(f"{key} 应为 dict")
                continue
            for sub_key, sub_schema_value in schema_value.items():
                if sub_key not in current_value:
                    issues.append(f"{key}.{sub_key}")
                    continue
                sub_value = current_value.get(sub_key)
                field_path = f"{key}.{sub_key}"
                if isinstance(sub_schema_value, dict) and not isinstance(sub_value, dict):
                    issues.append(f"{field_path} 应为 dict")
                elif isinstance(sub_schema_value, list):
                    _validate_list_shape(field_path, sub_value, sub_schema_value, issues)
                elif isinstance(sub_schema_value, str) and not isinstance(sub_value, str):
                    issues.append(f"{field_path} 应为字符串")
        elif isinstance(schema_value, list):
            _validate_list_shape(key, current_value, schema_value, issues)
        elif isinstance(schema_value, str) and not isinstance(current_value, str):
            issues.append(f"{key} 应为字符串")

    issues = _dedupe_keep_order(issues)
    return len(issues) == 0, issues


# ================== 内容质量校验 ==================
def _validate_cover_like_quality(slide_type: str, payload: dict, issues: List[str]) -> None:
    if slide_type == "end":
        if not payload:
            return
        text = payload.get("text")
        if text is None:
            return
        if not _is_non_empty_string(text, min_length=4):
            issues.append("data.text 为空或过短")
        elif _looks_like_placeholder(text):
            issues.append("data.text 含占位或模板化表述")
        return

    title = payload.get("title")
    text = payload.get("text")
    if not _is_non_empty_string(title, min_length=2):
        issues.append("data.title 为空或过短")
    elif _looks_like_placeholder(title):
        issues.append("data.title 含占位或模板化表述")

    if not _is_non_empty_string(text, min_length=6):
        issues.append("data.text 为空或过短")
    elif _looks_like_placeholder(text):
        issues.append("data.text 含占位或模板化表述")


def _validate_contents_quality(payload: dict, issues: List[str]) -> None:
    items = payload.get("items")
    if not isinstance(items, list) or not items:
        issues.append("data.items 不能为空")
        return
    normalized_items: List[str] = []
    for index, item in enumerate(items):
        if not _is_non_empty_string(item, min_length=2):
            issues.append(f"data.items[{index}] 为空或过短")
            continue
        normalized_items.append(_normalize_text(item))
    if len(normalized_items) != len(set(normalized_items)):
        issues.append("data.items 存在重复目录项")


def _validate_chart_item_quality(index: int, item: dict, issues: List[str]) -> None:
    title = item.get("title")
    chart_type = item.get("chartType")
    if not _is_non_empty_string(title, min_length=2):
        issues.append(f"data.items[{index}].title 为空或过短")
    if chart_type and chart_type not in ALLOWED_CHART_TYPES:
        issues.append(f"data.items[{index}].chartType 非受支持图表类型")
    if item.get("data") is None and item.get("series") is None:
        issues.append(f"data.items[{index}] 缺少图表数据")


def _validate_content_quality(payload: dict, required_schema: dict, issues: List[str]) -> None:
    title = payload.get("title")
    if not _is_non_empty_string(title, min_length=2):
        issues.append("data.title 为空或过短")
    elif _looks_like_placeholder(title):
        issues.append("data.title 含占位或模板化表述")

    items = payload.get("items")
    required_items = required_schema.get("data", {}).get("items") if isinstance(required_schema.get("data"), dict) else None
    min_expected_items = len(required_items) if isinstance(required_items, list) and required_items else 1

    if not isinstance(items, list) or len(items) < min_expected_items:
        issues.append("data.items 数量不足")
        return

    normalized_titles: List[str] = []
    normalized_texts: List[str] = []
    valid_content_count = 0

    for index, item in enumerate(items):
        if not isinstance(item, dict):
            issues.append(f"data.items[{index}] 应为 dict")
            continue

        if item.get("kind") == "chart":
            _validate_chart_item_quality(index, item, issues)
            valid_content_count += 1
            continue

        item_title = item.get("title")
        item_text = item.get("text")
        if not _is_non_empty_string(item_title, min_length=2):
            issues.append(f"data.items[{index}].title 为空或过短")
        elif _looks_like_placeholder(item_title):
            issues.append(f"data.items[{index}].title 含占位或模板化表述")
        else:
            normalized_titles.append(_normalize_text(item_title))

        if not _is_non_empty_string(item_text, min_length=16):
            issues.append(f"data.items[{index}].text 为空或过短")
        elif _looks_like_placeholder(item_text):
            issues.append(f"data.items[{index}].text 含占位或模板化表述")
        else:
            normalized_texts.append(_normalize_text(item_text))

        if _is_non_empty_string(item_title, min_length=2) and _is_non_empty_string(item_text, min_length=2):
            if _normalize_text(item_title) == _normalize_text(item_text):
                issues.append(f"data.items[{index}] 标题与正文重复")
            valid_content_count += 1

    if normalized_titles and len(normalized_titles) != len(set(normalized_titles)):
        issues.append("data.items 存在重复标题")
    if normalized_texts and len(normalized_texts) != len(set(normalized_texts)):
        issues.append("data.items 存在重复正文")
    if valid_content_count == 0:
        issues.append("data.items 缺少可用内容")


def validate_slide_quality(data: Any, required_schema: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """
    内容质量校验：
    - 不追求语义完美，但至少拦住明显不可交付的结果
    - 重点识别占位文案、过短正文、重复内容、错误图表结构等问题
    """
    issues: List[str] = []
    if not isinstance(data, dict):
        return False, ["输出不是 dict"]

    required_type = required_schema.get("type") if isinstance(required_schema, dict) else None
    slide_type = data.get("type")
    if required_type and slide_type != required_type:
        issues.append("type 与当前页面 schema 不一致")

    payload = data.get("data")
    if payload is not None and not isinstance(payload, dict):
        issues.append("data 应为 dict")
        payload = {}
    payload = payload or {}

    if slide_type in {"cover", "transition", "end"}:
        _validate_cover_like_quality(slide_type, payload, issues)
    elif slide_type == "contents":
        _validate_contents_quality(payload, issues)
    elif slide_type == "content":
        _validate_content_quality(payload, required_schema, issues)

    images = data.get("images")
    if images is not None:
        if not isinstance(images, list):
            issues.append("images 应为 list")
        else:
            for index, image in enumerate(images):
                if not isinstance(image, dict):
                    issues.append(f"images[{index}] 应为 dict")
                    continue
                if not _is_non_empty_string(image.get("src"), min_length=8):
                    issues.append(f"images[{index}].src 为空或过短")

    issues = _dedupe_keep_order(issues)
    return len(issues) == 0, issues


# ================== Checker / Controller 纯函数状态机 ==================
def build_validation_feedback(failure_stage: str, issues: List[str]) -> str:
    normalized_issues = _dedupe_keep_order(issues)
    issue_text = "；".join(normalized_issues) if normalized_issues else "未提供详细问题"
    if failure_stage == FAILURE_STAGE_PARSE:
        return f"校验失败：输出不是可解析 JSON。请严格输出单个 JSON 对象，不要添加解释性文字或 Markdown 代码块。问题：{issue_text}。"
    if failure_stage == FAILURE_STAGE_STRUCTURE:
        return f"校验失败：JSON 结构与当前页面 schema 不匹配。请补齐缺失字段、修正字段类型，并保持页面 type 与 schema 一致。问题：{issue_text}。"
    if failure_stage == FAILURE_STAGE_QUALITY:
        return f"校验失败：内容质量未达标。请保留当前页面结构，针对性修正文案空泛、重复、过短或缺少关键内容的问题。问题：{issue_text}。"
    return f"校验失败：{issue_text}。"


def build_validation_summary(failure_stage: Optional[str], issues: List[str]) -> str:
    if not failure_stage:
        return "校验结果：✅ 结构与内容质量均通过。"
    issue_text = "；".join(_dedupe_keep_order(issues)) if issues else "未提供详细问题"
    if failure_stage == FAILURE_STAGE_PARSE:
        return f"校验结果：❌ 解析失败，将触发重试或跳过策略。问题：{issue_text}"
    if failure_stage == FAILURE_STAGE_STRUCTURE:
        return f"校验结果：❌ 结构校验失败，将触发重试或跳过策略。问题：{issue_text}"
    return f"校验结果：❌ 内容质量校验失败，将触发重试或跳过策略。问题：{issue_text}"


def evaluate_checker_result(raw_text: Any, required_schema: Dict[str, Any]) -> CheckerOutcome:
    raw_string = str(raw_text or "").strip()
    parsed_data = only_json(raw_string)
    if parsed_data is None:
        issues = ["输出不是可解析 JSON"]
        return CheckerOutcome(
            passed=False,
            summary_text=build_validation_summary(FAILURE_STAGE_PARSE, issues),
            feedback=build_validation_feedback(FAILURE_STAGE_PARSE, issues),
            issues=issues,
            failure_stage=FAILURE_STAGE_PARSE,
            parsed_data=None,
            is_valid_json=False,
            structure_passed=False,
            quality_passed=False,
        )

    structure_passed, structure_issues = validate_slide(parsed_data, required_schema)
    if not structure_passed:
        return CheckerOutcome(
            passed=False,
            summary_text=build_validation_summary(FAILURE_STAGE_STRUCTURE, structure_issues),
            feedback=build_validation_feedback(FAILURE_STAGE_STRUCTURE, structure_issues),
            issues=structure_issues,
            failure_stage=FAILURE_STAGE_STRUCTURE,
            parsed_data=None,
            is_valid_json=False,
            structure_passed=False,
            quality_passed=False,
        )

    quality_passed, quality_issues = validate_slide_quality(parsed_data, required_schema)
    if not quality_passed:
        return CheckerOutcome(
            passed=False,
            summary_text=build_validation_summary(FAILURE_STAGE_QUALITY, quality_issues),
            feedback=build_validation_feedback(FAILURE_STAGE_QUALITY, quality_issues),
            issues=quality_issues,
            failure_stage=FAILURE_STAGE_QUALITY,
            parsed_data=parsed_data,
            is_valid_json=True,
            structure_passed=True,
            quality_passed=False,
        )

    return CheckerOutcome(
        passed=True,
        summary_text=build_validation_summary(None, []),
        feedback=None,
        issues=[],
        failure_stage=None,
        parsed_data=parsed_data,
        is_valid_json=True,
        structure_passed=True,
        quality_passed=True,
    )


def ensure_loop_state_initialized(state: Dict[str, Any]) -> Dict[str, Any]:
    if state.get("retry_count_map") is None:
        state["retry_count_map"] = {}
    if state.get("generated_slides_content") is None:
        state["generated_slides_content"] = []
    if state.get("writer_should_clear_history") is None:
        state["writer_should_clear_history"] = True
    if "last_validation_issues" not in state or state.get("last_validation_issues") is None:
        state["last_validation_issues"] = []
    return state


def apply_checker_outcome_to_state(state: Dict[str, Any], outcome: CheckerOutcome) -> Dict[str, Any]:
    ensure_loop_state_initialized(state)
    state["is_valid_json"] = outcome.is_valid_json
    state["last_slide_json"] = outcome.parsed_data
    state["last_validation_passed"] = outcome.passed
    state["last_structure_validation_passed"] = outcome.structure_passed
    state["last_quality_validation_passed"] = outcome.quality_passed
    state["last_validation_failure_stage"] = outcome.failure_stage
    state["last_validation_issues"] = list(outcome.issues)
    state["last_validation_feedback"] = outcome.feedback
    state["last_checker_summary"] = outcome.summary_text
    return state


def build_slide_output_text(last_written_raw: Any, last_slide_json: Any) -> Optional[str]:
    if isinstance(last_slide_json, dict):
        return json.dumps(last_slide_json, ensure_ascii=False)
    if last_written_raw is None:
        return None
    return str(last_written_raw)


def _append_accumulated(state: Dict[str, Any], item: Any) -> None:
    accumulated = state.get("generated_slides_content")
    if accumulated is None:
        accumulated = []
        state["generated_slides_content"] = accumulated
    accumulated.append(item)


def _reset_current_slide_transient_state(state: Dict[str, Any]) -> None:
    state["last_written_raw"] = None
    state["last_slide_json"] = None
    state["is_valid_json"] = False
    state["last_validation_passed"] = None
    state["last_structure_validation_passed"] = None
    state["last_quality_validation_passed"] = None
    state["last_validation_failure_stage"] = None
    state["last_validation_issues"] = []
    state["last_validation_feedback"] = None
    state["last_checker_summary"] = None


def advance_or_retry_after_validation(state: Dict[str, Any], *, max_retries: int = 3) -> ControllerDecision:
    ensure_loop_state_initialized(state)
    slides_plan_num = int(state.get("slides_plan_num", 0))
    current_slide_index = int(state.get("current_slide_index", 0))
    validation_passed = bool(state.get("last_validation_passed", False))
    retry_map = state.get("retry_count_map")
    if retry_map is None:
        retry_map = {}
        state["retry_count_map"] = retry_map
    current_retries = int(retry_map.get(current_slide_index, 0))

    if validation_passed:
        slide_payload = state.get("last_slide_json")
        if slide_payload is not None:
            _append_accumulated(state, slide_payload)
        else:
            _append_accumulated(state, state.get("last_written_raw"))

        output_text = build_slide_output_text(state.get("last_written_raw"), state.get("last_slide_json"))
        retry_map[current_slide_index] = 0
        state["current_slide_index"] = current_slide_index + 1
        state["writer_should_clear_history"] = True
        state["last_controller_action"] = "advance"
        _reset_current_slide_transient_state(state)

        next_slide_index = int(state.get("current_slide_index", 0))
        should_escalate = slides_plan_num > 0 and next_slide_index >= slides_plan_num
        return ControllerDecision(
            action="advance",
            retry_count=0,
            current_slide_index=current_slide_index,
            next_slide_index=next_slide_index,
            output_text=output_text,
            should_escalate=should_escalate,
            degraded=False,
            failure_stage=None,
        )

    current_retries += 1
    retry_map[current_slide_index] = current_retries
    failure_stage = state.get("last_validation_failure_stage")
    if current_retries <= max_retries:
        state["writer_should_clear_history"] = False
        state["last_controller_action"] = "retry"
        return ControllerDecision(
            action="retry",
            retry_count=current_retries,
            current_slide_index=current_slide_index,
            next_slide_index=current_slide_index,
            output_text=None,
            should_escalate=False,
            degraded=False,
            failure_stage=failure_stage,
        )

    output_text = build_slide_output_text(state.get("last_written_raw"), state.get("last_slide_json"))
    state["current_slide_index"] = current_slide_index + 1
    state["writer_should_clear_history"] = True
    state["last_controller_action"] = "degrade"
    state["last_degraded_failure_stage"] = failure_stage
    state["last_degraded_feedback"] = state.get("last_validation_feedback")
    retry_map[current_slide_index] = 0
    _reset_current_slide_transient_state(state)

    next_slide_index = int(state.get("current_slide_index", 0))
    should_escalate = slides_plan_num > 0 and next_slide_index >= slides_plan_num
    return ControllerDecision(
        action="degrade",
        retry_count=current_retries,
        current_slide_index=current_slide_index,
        next_slide_index=next_slide_index,
        output_text=output_text,
        should_escalate=should_escalate,
        degraded=True,
        failure_stage=failure_stage,
    )


if __name__ == "__main__":
    sample_data = {
        "data": {
            "items": [
                {
                    "text": "生成式AI通过学习海量数据，可自动生成符合语境的文章、脚本和配乐。这降低了内容生产门槛，提升企业营销效率。",
                    "title": "内容创作行业全面变革，自动化生成高质量文章、视频和音乐",
                },
                {
                    "text": "AI模型能预测分子特性与生物活性，加速候选药物筛选过程，缩短创新药上市时间。",
                    "title": "药物研发周期缩短，AI辅助设计新分子结构",
                },
            ],
            "title": "生成式AI的商业应用",
        },
        "images": [
            {
                "alt": "technology background",
                "height": 1080,
                "id": "image-1",
                "src": "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg",
                "width": 1920,
            }
        ],
        "type": "content",
    }
    current_slide_schema = {
        "data": {
            "items": [
                {"text": "Detailed content about A", "title": "A"},
                {"text": "Detailed content about B", "title": "B"},
            ],
            "title": "AI 与商业应用",
        },
        "type": "content",
    }

    print(validate_slide(sample_data, current_slide_schema))
    print(validate_slide_quality(sample_data, current_slide_schema))
